assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    java:           '%java_path%'
    bundles: [ ArcmediaCmsBundle ]
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: '%kernel.root_dir%/Resources/node_modules/.bin/uglifyjs'
        uglifycss:
            bin: '%kernel.root_dir%/Resources/node_modules/.bin/uglifycss'
        yui_css:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
        yui_js:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
