imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: assetic.yml }


framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies:
        - 10.255.0.0/16
        - 103.232.34.0/28
        - 162.248.54.0/23
        - 192.83.254.176/28
        - 192.168.56.0/24
        - 195.21.32.32/28
        - 195.21.35.160/28
        - 195.190.78.0/29
        - 195.190.79.240/28
        - 213.39.7.208/28
        - 213.39.44.80/28
        - 213.251.8.0/28
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    exception_controller: 'arcmedia.controller.exception:showAction'
    strict_variables: false
    date:
        format: Y-m-d\TH:i:s

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            datetime_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    in_memory_user_provider:
        alias: security.user.provider.concrete.in_memory
#    app.locale_listener:
#        class: Arcmedia\CommonBundle\EventListener\LocaleListener
#        arguments: ["%kernel.default_locale%", @security.token_storage]
#        tags:
#            - { name: kernel.event_subscriber }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

ivory_ck_editor:
    configs:
        admin_config:
            toolbarGroups:
              - { name: 'document', groups: [ 'mode', 'document', 'doctools' ] }
              - { name: 'clipboard', groups: [ 'clipboard', 'undo' ] }
              - { name: 'links', groups: [ 'links' ] }
              -	{ name: 'insert', groups: [ 'insert' ] }
              -	{ name: 'tools', groups: [ 'tools' ] }
              - { name: 'about', groups: [ 'about' ] }
              -	'/'
              -	{ name: 'styles', groups: [ 'styles' ] }
              -	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] }
              -	{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align' ] }
            removeButtons: 'Font,FontSize,Flash,Save,NewPage,Print,Smiley,SpecialChar,Iframe'
