<?php

namespace Arcmedia\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Arcmedia\CmsBundle\Entity\ArcmediaPage;


/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns set of pages according to limit
     *
     * @param int  $limit
     * @return Query
     */
    public function listPages($limit = ArcmediaPage::NUM_ITEMS)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select(['p'])
            ->from('ArcmediaCmsBundle:ArcmediaPage', 'p')
            ->orderBy('p.order', 'ASC')
            ->setMaxResults($limit);

        return $qb->getQuery();
    }

    /**
     * Returns set of pages according to limit
     *
     * @param int  $limit
     * @return ArcmediaPage[]|Null
     */
    public function getActivePages()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select(['p'])
            ->from('ArcmediaCmsBundle:ArcmediaPage', 'p')
            ->where('p.active = :state')
            ->orderBy('p.order', 'ASC')
            ->setParameter('state',true)
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * Returns max order
     *
     * @param int  $limit
     * @return int
     */
    public function getMaxOrder()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('max(p.order)')
            ->from('ArcmediaCmsBundle:ArcmediaPage', 'p')
            ->where('p.active = :state')
            ->orderBy('p.order', 'DESC')
            ->setParameter('state',true)
            ->setMaxResults(1);
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
