Arcmedia\CmsBundle\Entity\ArcmediaPage:
    type: entity
    table: arcmedia_page
    repositoryClass: Arcmedia\CmsBundle\Repository\PageRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        active:
            type: boolean
            nullable: false
            comment: ''
        order:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: '`order`'
        title:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        alias:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
